version: "3"
services:
  postgresserver:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=game_vision_db
    ports:
      - "5432:5432"

  web-api:
    build: .
    environment:
      GameVisionDbConnectionString: "Host=postgresserver;Port=5432;Database=game_vision_db;Username=postgres;Password=123456;Pooling=false;"
      AwsS3AccessKey: ""
      AwsS3SecretKey: ""
      AwsS3RootBucket: "game-vision-dev"
    ports:
      - "8000:8080"
      - "8090:8081"
    links:
      - postgresserver
    depends_on:
      - "postgresserver"
    deploy:
      mode: replicated
      replicas: 1
